`default_nettype none

module SidebandTx (
  input  wire logic         clock,
  input  wire logic         reset_n,
  input  wire logic [127:0] din,
  input  wire logic         valid,

  output var  logic         ready,
  output var  logic         dout,
  output var  logic         clk_out,

  output var  logic [2:0]   dbg_state,
  output var  logic [63:0]  dbg_shiftReg,
  output var  logic [63:0]  dbg_payloadReg,
  output var  logic [6:0]   dbg_bitsLeft,
  output var  logic [4:0]   dbg_gapCount,
  output var  logic         dbg_payloadPending
);

  typedef enum logic [2:0] {
    State_IDLE         = 3'd0,
    State_SEND_HEADER  = 3'd1,
    State_PAYLOAD_GAP  = 3'd2,
    State_SEND_PAYLOAD = 3'd3,
    State_FINAL_GAP    = 3'd4
  } State_t;

  localparam logic [4:0] OPCODE_MSG_WITH_DATA = 5'b11011;

  State_t state;

  logic [63:0] shiftReg;
  logic [63:0] payloadReg;
  logic [6:0]  bitsLeft;
  logic [4:0]  gapCount;
  logic        payloadPending;

  logic doutReg;

  /*
   * Clock-enable request generated by the positive-edge FSM.
   */
  logic txClockEnableRequest;

  /*
   * Actual clock enable captured while clock is low.
   */
  logic txClockEnable;

  /*
   * Combinational output assignments.
   */
  always_comb begin
    ready = (state == State_IDLE);

    /*
     * The output clock retains the same phase as clock.
     * txClockEnable changes only on falling edges.
     */
    clk_out = clock & txClockEnable;

    /*
     * doutReg changes on rising edges.
     */
    dout = doutReg;

    dbg_state          = state;
    dbg_shiftReg       = shiftReg;
    dbg_payloadReg     = payloadReg;
    dbg_bitsLeft       = bitsLeft;
    dbg_gapCount       = gapCount;
    dbg_payloadPending = payloadPending;
  end

  /*
   * Glitch-free clock-enable capture.
   *
   * The gated clock is enabled and disabled only while clock is low.
   */
  always_ff @(negedge clock or negedge reset_n) begin
    if (!reset_n)
      txClockEnable <= 1'b0;
    else
      txClockEnable <= txClockEnableRequest;
  end

  /*
   * Rising-edge serializer.
   *
   * doutReg changes at the same source-clock edge that produces the
   * corresponding clk_out rising edge.
   */
  always_ff @(posedge clock or negedge reset_n) begin
    if (!reset_n) begin
      state                <= State_IDLE;
      shiftReg             <= 64'b0;
      payloadReg           <= 64'b0;
      bitsLeft             <= 7'b0;
      gapCount             <= 5'b0;
      payloadPending       <= 1'b0;
      doutReg              <= 1'b0;
      txClockEnableRequest <= 1'b0;
    end else begin
      case (state)

        State_IDLE: begin
          doutReg              <= 1'b0;
          txClockEnableRequest <= 1'b0;

          if (valid && ready) begin
            /*
             * Capture the input transaction.
             *
             * doutReg is not loaded here because txClockEnable cannot
             * become active until the following falling edge.
             */
            shiftReg       <= din[63:0];
            payloadReg     <= din[127:64];
            bitsLeft       <= 7'd64;
            payloadPending <=
                (din[4:0] == OPCODE_MSG_WITH_DATA);

            /*
             * Request clock activation. txClockEnable will capture
             * this request at the next falling edge.
             */
            txClockEnableRequest <= 1'b1;
            state                <= State_SEND_HEADER;
          end
        end

        State_SEND_HEADER: begin
          /*
           * Launch the current serialized bit on the rising edge.
           */
          doutReg <= shiftReg[0];

          if (bitsLeft == 7'd1) begin
            /*
             * The last header bit is launched here.
             *
             * Request clock disable. The actual clock enable is
             * cleared on the following falling edge, preserving the
             * complete final high pulse.
             */
            bitsLeft             <= 7'd0;
            gapCount             <= 5'd31;
            txClockEnableRequest <= 1'b0;

            if (payloadPending)
              state <= State_PAYLOAD_GAP;
            else
              state <= State_FINAL_GAP;
          end else begin
            shiftReg <= {1'b0, shiftReg[63:1]};
            bitsLeft <= bitsLeft - 7'd1;
          end
        end

        State_PAYLOAD_GAP: begin
          doutReg              <= 1'b0;
          txClockEnableRequest <= 1'b0;

          if (gapCount == 5'd0) begin
            /*
             * Load the payload.
             *
             * Its first bit will be launched on the next rising edge
             * after txClockEnable becomes active.
             */
            shiftReg <= payloadReg;
            bitsLeft <= 7'd64;

            txClockEnableRequest <= 1'b1;
            state                <= State_SEND_PAYLOAD;
          end else begin
            gapCount <= gapCount - 5'd1;
          end
        end

        State_SEND_PAYLOAD: begin
          /*
           * Launch the current payload bit.
           */
          doutReg <= shiftReg[0];

          if (bitsLeft == 7'd1) begin
            bitsLeft             <= 7'd0;
            payloadPending       <= 1'b0;
            gapCount             <= 5'd31;
            txClockEnableRequest <= 1'b0;
            state                <= State_FINAL_GAP;
          end else begin
            shiftReg <= {1'b0, shiftReg[63:1]};
            bitsLeft <= bitsLeft - 7'd1;
          end
        end

        State_FINAL_GAP: begin
          doutReg              <= 1'b0;
          txClockEnableRequest <= 1'b0;

          if (gapCount == 5'd0) begin
            state <= State_IDLE;
          end else begin
            gapCount <= gapCount - 5'd1;
          end
        end

        default: begin
          state                <= State_IDLE;
          shiftReg             <= 64'b0;
          payloadReg           <= 64'b0;
          bitsLeft             <= 7'b0;
          gapCount             <= 5'b0;
          payloadPending       <= 1'b0;
          doutReg              <= 1'b0;
          txClockEnableRequest <= 1'b0;
        end

      endcase
    end
  end

endmodule

`default_nettype wire

