// Run the simulator from this test directory.
// Packages precede modules; all harnesses use the production serial top.
timescale.sv
../src/Types.sv
../src/Parameters.sv
../src/States.sv
../src/sidebandNode.sv
../src/Rdi.sv
../src/Fdi.sv
../src/D2DAdapterConstants.sv
../src/RdiLinkManagementConstants.sv
../src/SidebandMsgGenerator_corregido.sv
../src/D2DAdapterLinkMgmtLtsmSBTop.sv
../src/D2DAdapterLinkMgmtLtsmTop_corrected.sv
../src/D2DAdapterLinkMgmtTop.sv
../src/LinkManagementController.sv
../src/LinkMgmtSidebandPacketArbiter.sv
../src/LinkTrainingFSM.sv
../src/LtsmSidebandRxPulseAdapter.sv
../src/LtsmSidebandTxCapture.sv
../src/MBInitFSM.sv
../src/MBTrainFSM.sv
../src/MBTrain_DataTrainCenter1.sv
../src/MBTrain_DataTrainCenter1SweepEngine.sv
../src/MBTrain_DataTrainCenter2.sv
../src/MBTrain_DataTrainCenter2SweepEngine.sv
../src/MBTrain_DataTrainVrefFSM.sv
../src/MBTrain_DataVrefFSM.sv
../src/MBTrain_DataVrefStateCore.sv
../src/MBTrain_DataVrefSweepEngine.sv
../src/MBTrain_LinkSpeed.sv
../src/MBTrain_RxClkCalFSM.sv
../src/MBTrain_RxDeskewFSM.sv
../src/MBTrain_RxDeskewSweepEngine.sv
../src/MBTrain_SpeedIdleFSM.sv
../src/MBTrain_TxSelfCalFSM.sv
../src/MBTrain_ValTrainCenterFSM.sv
../src/MBTrain_ValTrainCenterSweepEngine.sv
../src/MBTrain_ValTrainVrefFSM.sv
../src/MBTrain_ValVrefFSM.sv
../src/MBTrain_ValidVrefStateCore.sv
../src/MBTrain_ValidVrefSweepEngine.sv
../src/RdiLinkManagementController.sv
../src/RdiTimeoutController.sv
../src/RxInitD2CPointTestReceiverFSM.sv
../src/RxInitD2CPointTestSenderFSM.sv
../src/SideBandModule.sv
../src/SidebandRx.sv
../src/SidebandTx.sv
../src/StallController.sv
../src/TxInitD2CPointTestReceiverFSM.sv
../src/TxInitD2CPointTestSenderFSM.sv
../src/UCIePhyRegisterBlock.sv
D2DAdapterLinkMgmtTbSerialBfm.sv
D2DAdapterLinkMgmtTbSerialLinkChecker.sv
D2DAdapterLinkMgmtLtsmDualDieHarness.sv
D2DAdapterLinkMgmtLtsmDualDieDirectedBackpressureHarness.sv
D2DAdapterLinkMgmtLtsmIntegrated128Harness.sv
D2DAdapterLinkMgmtLtsmDualDieBringUpSpec_tb.sv
D2DAdapterLinkMgmtLtsmDualDieBackpressureSpec_tb.sv
D2DAdapterLinkMgmtTopIntegrated128Spec_tb.sv
